#!/usr/bin/env python3
'''
        File:           gerrit-jira-hook.py
        Author:         Cedric Schwyter
        Version:        1.0
'''
import os
import sys
import re
import requests
import subprocess
import configparser
import getopt
import logging as log
import jira


log_path = os.path.join(os.path.dirname(__file__), 'hooks.log')
FORMAT = '%(asctime)-12s %(levelname)-8s %(message)s'
log.basicConfig(format=FORMAT, filename=log_path, level=log.DEBUG)

config_path = os.path.join(os.path.dirname(__file__), 'gerrit-jira-hook.config')
config = configparser.RawConfigParser()
config.read(config_path)

JIRA_URL = config.get('gerrit-jira-hook', 'jira_url')
JIRA_USER = config.get('gerrit-jira-hook', 'jira_user')
JIRA_PASS = config.get('gerrit-jira-hook', 'jira_pass')

PROJECTS = config.get('gerrit-jira-hook', 'gerrit_projects').split(',')

GERRIT_USER = config.get('gerrit-jira-hook', 'gerrit_user')
GERRIT_SSHD = 'ssh -p 29418 ' + GERRIT_USER + '@localhost gerrit'

COMMENT_TEMPLATE = """Latest change for {issue_id}
*{change_owner_username}* pushed a commit: 
{change_url}
Subject: *{subject}*
Project: {project} 
Branch: {branch} 
Change-Id: {change_id} 
Commit: {commit} 
This change was reviewed and approved by *{submitter_username}*.
"""

COMMENT_TEMPLATE_REGEX = "Latest change for ([A-Z]+-[0-9]+)"


def init():
    try:
        open(log_path, 'a+').close()
        if len(sys.argv) < 2:
            log.error('Insufficient arguments supplied')
            exit()
        arguments = ['change', 'change-url', 'change-owner',
                    'change-owner-username', 'project',
                    'commit', 'branch', 'submitter',
                    'submitter-username' 'newrev', 'topic']
        optlist, args = getopt.getopt(sys.argv[1:], '', [i + '=' for i in arguments])
        values = {}
        for o, a in optlist:
            values[o[2:]] = a
            log.debug('CLI-Option ' + o + ':\t\t' + a)
        if PROJECTS == 'All-Projects' or (values['project'] != None and values['project'] in PROJECTS):
            jira_hook(values)
        else:
            exit(1)
    except PermissionError:
        print('Permission Error creating/opening log at "' + log_path + '"')
        raise


def find_issue_identifiers(change, jira_instance):
    log.debug('Running Gerrit query command...')
    proc = subprocess.Popen([GERRIT_SSHD, ' query --format TEXT change:', change, ' limit:1'], 
        stdout=subprocess.PIPE, shell=True)
    (out, status) = proc.communicate()
    if status != 0:
        log.error('Failed to run Gerrit query command')
        exit(1)
    else:
        commit_information = {}
        commit_information['subject'] = re.search('subject: (.*)\n', out).group(1)
        log.debug('Change-Id query delivered the following subject result: ' + commit_information['subject'])
        commit_information['project'] = re.search('project: (.*)\n', out).group(1)
        log.debug('Change-Id query delivered the following project result: ' + commit_information['project'])
        log.debug('Detecting issue-id\'s...')
        issues = []
        issue_pattern = '(%s-[0-9]+)'
        projects = jira_instance.projects()
        for project in projects:
            matches = re.findall(issue_pattern % project, subject)
            for m in matches:
                log.debug('Found issue-id: ' + m)
                issues.append(m)
        return commit_information, issues


def generate_comment(values, commit_information, issue_id):
    return COMMENT_TEMPLATE.format(change_owner_username=values['change-owner-username'],
                                   issue_id=issue_id,
                                   change_url=values['change-url'],
                                   subject=commit_information['subject'],
                                   project=commit_information['project'],
                                   branch=values['branch'],
                                   change_id=values['change'],
                                   commit=values['commit'],
                                   submitter_username=values['submitter-username'])


def jira_hook(values):
    '''
    The main function for the Gerrit-hook to post a comment on a JIRA-ticket 
    with the Change-Id and other information whenever an issue-id is detected in
    a commit-message. The issue-id is extracted from the commig-message by 
    running a regular expression over it and seeing if it matches anything.
    '''
    log.debug('Executing gerrit-jira-hook...')
    log.debug('Connecting to Jira-instance running at "' + JIRA_URL + '"...')
    try:
        log.debug('Logging in to Jira as user "' + JIRA_USER + '"...')
        jira_instance = jira.JIRA(JIRA_URL, basic_auth=(JIRA_USER, JIRA_PASS), logging=True)
        log.debug('Logged in to Jira')
    except (requests.exceptions.ConnectionError, jira.exceptions.JIRAError) as e:
        log.error('Connection to "' + JIRA_URL + '" as user "' + JIRA_USER
            + '" failed')
        exit(1)
    except requests.exceptions.ConnectTimeout:
        log.error('Connection to "' + JIRA_URL + '" as user "' + JIRA_USER
            + '" timed out')
        exit(1)
    commit_information, issue_ids = find_issue_identifiers(values['change'], jira_instance)
    for issue_id in issue_ids:
        log.debug('Generating comment for issue "' + issue_id + '"...')
        commit_information = {'project': 'service/tradelifecycle', 'subject': 'TestCommit'}
        comment = generate_comment(values, commit_information, issue_id)
        try:
            log.debug('Trying to find and delete old comments on issue...')
            issue = jira_instance.issue(issue_id)
            comments = issue.fields.comment.comments
            regex = re.compile(COMMENT_TEMPLATE_REGEX)
            for c in comments:
                if regex.match(c.body):
                    log.debug('Deleting comment...')
                    c.delete()
                    log.debug('Comment deleted')
            log.debug('Posting comment to issue "' + issue_id + '"...')
            jira_instance.add_comment(issue_id, comment)
            log.debug('Posted comment to issue "' + issue_id + '"')
        except:
            log.error('Failed to update issue "' + issue_id 
                + '". This is bad.\n\n\t\t\t\t\t\t\t\t\t\tV E R Y   B A D.\n')
            raise
            exit(1)
    else:
        log.debug('No issue-id found, exiting gracefully...')
        exit(0)


if __name__ == "__main__":
    init()
